<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1492</name>
   <tag></tag>
   <elementGuidId>9f1ceb1b-d111-4f11-bf66-969a50874a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-52</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>378b5d26-7989-404e-860f-d2abe456a954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-52</value>
      <webElementGuid>233fda85-93a9-41ba-a87a-3728699c95c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56eabca7-745b-499d-aada-769fbf7179bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-52&quot;)</value>
      <webElementGuid>7c2154db-8e93-492f-a00f-e72ece661fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-52']</value>
      <webElementGuid>225a9485-50b6-4c6a-87a5-45d29493d881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>28bf7d15-c1fb-4eaf-9695-fa37866f53f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>028267dc-dfdd-4e77-ba44-2c22007eff3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-52' and @type = 'text']</value>
      <webElementGuid>0fef9221-0754-4e50-8969-7f2b9d7aeca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
