<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_input-1486</name>
   <tag></tag>
   <elementGuidId>58535299-eb1c-4ed3-ba65-fbd73cd102e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-46']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93e0ce4e-2058-40f5-be0d-7125fecb4044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-46</value>
      <webElementGuid>4e289f8b-799a-4b1f-907a-a1107b078ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cac725e2-6276-4e30-bcc6-1c698f58a62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-46&quot;)</value>
      <webElementGuid>f98caa86-61d0-439b-9de9-8039aea3ce92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-46']</value>
      <webElementGuid>1ad1f41d-9fa6-47be-94e5-79f7271142df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>733202ce-d0fe-4c7c-a505-2b0c5c2c35f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58e5784f-0046-4eed-b099-5eeb30bac2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-46' and @type = 'text']</value>
      <webElementGuid>a82b4110-c059-4440-ac6a-30903bec8042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
