<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sony PS5  play has no limits  Rp 299DetailBeli</name>
   <tag></tag>
   <elementGuidId>0f70fa39-4f7e-44dd-8b65-4a121e64875e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='72']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#72</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5197dd2a-8ebc-44b0-b4d5-3aac07956ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>bafd6dcd-087b-4998-834e-ade95c9051e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-lg-3 col-6</value>
      <webElementGuid>7e700e77-5414-4380-a107-d04c98c90391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sony PS5  play has no limits   Rp 299DetailBeli</value>
      <webElementGuid>1e47b66b-92bc-4b9d-8ed8-b92abfd0aaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;72&quot;)</value>
      <webElementGuid>606a55cc-eb83-4c86-9807-dd5a0082a79b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='72']</value>
      <webElementGuid>7a18e318-7576-40f2-b947-c71d42a209b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div</value>
      <webElementGuid>76a8ee56-a777-4743-852f-e3322ed01bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='g'])[1]/following::div[11]</value>
      <webElementGuid>1e541d1e-8909-466b-a0a9-bdcc93658b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[21]</value>
      <webElementGuid>7b7b2750-6345-4e27-a5b5-d52afa9b8bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>f480e8f3-fd96-4226-afeb-acccabbcfaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '72' and (text() = ' Sony PS5  play has no limits   Rp 299DetailBeli' or . = ' Sony PS5  play has no limits   Rp 299DetailBeli')]</value>
      <webElementGuid>c48a3de9-2f5a-44cc-8e21-2669ce143787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
