<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gaming</name>
   <tag></tag>
   <elementGuidId>5a9e5505-a403-4c87-b3a7-d7580d66037c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-1008-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-1008-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d1b55fb-7477-4099-b073-e85d5fcb74a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84c4bcb2-beaf-4468-a1af-fc8a9f6ef406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e5977fb-6b9f-4af5-ba44-3b220802b954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-item-1008-3</value>
      <webElementGuid>a6f0062e-b694-480a-9850-2882ee36f9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>063c3021-a5ae-4725-9fea-7e5502f50d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item v-list-item--link theme--light</value>
      <webElementGuid>858cefb2-2dbd-4318-95f2-69c983b263ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gaming</value>
      <webElementGuid>21727bc8-0ae0-4643-a224-e0ccbc8ce1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-1008-3&quot;)</value>
      <webElementGuid>2ab8a7c6-76c5-4f2f-bc9d-faa7577d7dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ede2a861-4c4b-4203-bd71-7d479e1836fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>1625bbd5-9e02-4e3f-bc5d-4bcbc88fc71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gaming</value>
      <webElementGuid>ed2d5966-153c-4b36-8eb4-0e358ef18c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-2988-0&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>f95adde9-8224-4672-8b28-6ac57ac60d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='list-item-1008-3']</value>
      <webElementGuid>349f4c2c-80f6-4a34-8ccd-cf4b662a0515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-16']/div[4]</value>
      <webElementGuid>4eb15272-c691-40ba-8eb2-2231e8bbe076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[3]/following::div[1]</value>
      <webElementGuid>685a4106-e104-40e2-a6b6-b614e5dcee38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[2]/following::div[4]</value>
      <webElementGuid>be50821b-f9bd-45e2-945f-31cf171b4c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dolanan'])[1]/preceding::div[3]</value>
      <webElementGuid>28c39e64-cfa5-419a-a619-a47c4deb34b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>5591aee5-cc9a-4e99-959c-3544ac48a724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'list-item-1008-3' and (text() = 'gaming' or . = 'gaming')]</value>
      <webElementGuid>c6c4f73e-f1a1-43da-bef2-dc24764ccb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-2988-0']/div</value>
      <webElementGuid>36269306-bbc6-4cf3-819d-3bb133eb1d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[312]/following::div[4]</value>
      <webElementGuid>1da1903a-8e61-4db0-883c-8f6c6d9dc8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[312]/following::div[4]</value>
      <webElementGuid>c0b77ea8-9099-4d83-a0aa-c45279b96361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[2]/preceding::div[2]</value>
      <webElementGuid>5c67f466-db17-468d-84e8-59e88625673e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>26c44273-0909-4a09-89ca-d966165c8d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'gaming' or . = 'gaming')]</value>
      <webElementGuid>5ea799ab-7a33-452a-9a71-d356a0eb1701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
