<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1454</name>
   <tag></tag>
   <elementGuidId>d5fd5687-6bcc-4179-8bb6-7d1eb718a14c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1454</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1454']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80088b4-7fe2-462b-8879-ea3558215b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1454</value>
      <webElementGuid>6d39d1ef-3ca4-499e-9c33-222a6608362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4540806-d4b1-4f42-b5a2-0b34ef8b1466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1454&quot;)</value>
      <webElementGuid>e9022a68-06da-4f5b-b73c-3af319312d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1454']</value>
      <webElementGuid>0b8b9bec-6fee-4e0a-aebc-cdf43152f639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>c28e8c84-37a6-4f3e-a4c3-fa36af3389b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>56a4ab0f-7c98-4547-8282-1ea5b33d6de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1454' and @type = 'text']</value>
      <webElementGuid>0ffb0045-8ad2-4dd1-9bfa-eed7ab768704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
