<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1457</name>
   <tag></tag>
   <elementGuidId>b8e0ed48-5d11-43ec-9eeb-e430b46c9798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1457</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1457']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db0d17d2-0493-4f76-9984-3ddb6bbcbfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1457</value>
      <webElementGuid>a79fc982-54f1-4580-bf87-fe81895247ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c01b3c2-0745-4da5-ac58-30d87fe79b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1457&quot;)</value>
      <webElementGuid>da269972-5f5d-47fd-b532-428554d4c19e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1457']</value>
      <webElementGuid>3cef3b51-8e18-4fc9-97f1-8a40fc5643a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>3395a798-96b8-4612-b206-116d131c7e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>b70845a5-f65b-4fe8-8d7a-b21651a366ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1457' and @type = 'text']</value>
      <webElementGuid>cdf4ce6a-4118-47a0-98b0-27dc615671ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
