<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1472</name>
   <tag></tag>
   <elementGuidId>357fe122-5e1b-4259-8960-7c71b81b1003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1472</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1472']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd51eb48-8b1b-460e-acad-164c17ef94ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1472</value>
      <webElementGuid>0a0316e6-509b-4b49-847e-6d277a3bf110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01b81465-2bb9-4c64-9303-8179b1003e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1472&quot;)</value>
      <webElementGuid>2547bc79-5184-4fe2-ac66-82ba2ca93fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1472']</value>
      <webElementGuid>ac323b0d-bb0f-4b23-b73c-7fa0ad92e228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>9cbcc130-3168-47fe-8a11-4018657a8f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>976589ec-e6a1-4b03-ad7b-b211b4df696b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1472' and @type = 'text']</value>
      <webElementGuid>e976d927-0266-4d9d-9223-83dc9d71539a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
