<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1475</name>
   <tag></tag>
   <elementGuidId>a83bcce8-9ae5-4355-821d-d11fa40ddbe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1475</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1475']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89748d8b-d3b2-40ac-85aa-b8124a9c0570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1475</value>
      <webElementGuid>adce11b5-2f88-445b-b0fb-06253f9f4d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2de8d800-08d6-4766-b1e8-eb8fb6ac98b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1475&quot;)</value>
      <webElementGuid>0d160cd8-5873-44d6-a08b-e554598f5539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1475']</value>
      <webElementGuid>003282c5-b537-4474-9cfd-c7908efd21b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>abc7a93c-c240-46bd-b41a-6ac493a1f610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d227f800-8fb5-44ec-a61b-3d4befd7376a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1475' and @type = 'text']</value>
      <webElementGuid>d2267fde-06b2-4c8a-8945-92b22a23ae6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
